### ISSUE TITLE
onMouseLeave doesn't trigger onPanEnd

### ISSUE THREAD

**Issue by RobrechtM** [woutervh-/react-pan-and-zoom-hoc#3] opened 2018-05-07 09:43 UTC
When panning and your mouse leaves the bounds of the component, you expect the panning to stop. 
When you release the mouse and re-enter the component, it is still panning, even though the user isn't holding the mouse down.
A more expected behaviour is that the panning simply stops when you leave the component.

**Comment by woutervh-** [comment] 2018-05-07 12:02
Hi @RobrechtM ,

Let me understand more clearly, do you want:
- the panning to stop as soon as the mouse leaves the box, even if the user is still holding down the mouse button, or
- the panning to stop when the user lets go of the mouse button, regardless of whether the mouse is still inside the component?

Thanks

**Comment by RobrechtM** [comment] 2018-05-08 06:32
Thanks for your quick response, and interesting remark. 
I think it makes more sense to implement the second one. When the user enters the box with the mouse still down, the panning should continue.

**Comment by woutervh-** [comment] 2018-05-08 09:19
Hi @RobrechtM ,

I've published version 1.2.0, and to remain backwards compatible have kept the old behavior and added a new flag:
https://github.com/woutervh-/react-pan-and-zoom-hoc/blob/25dbf48844540bc1094579e760148a795971ebee/examples/main.js#L33

Using the new flag you can choose to ignore panning when the mouse exits the element.
I also changed the panning values to represent the center of the element, instead of the offset. X and Y are inverted (* -1). Zooming with the wheel should also be fixed by this.

Please let me know if this is working as intended for you.

**Comment by woutervh-** [comment] 2018-09-06 08:51
Closing for housekeeping purposes.

**Closed by woutervh-** 2018-09-06 08:51 UTC
